name       : kdecoration
version    : 5.14.0
release    : 26
source     :
    - https://cdn.download.kde.org/stable/plasma/5.14.0/kdecoration-5.14.0.tar.xz : f55bc460325a41de58c445a8d10eeecdfd127f3edc3da2b0a0a1d28b3da0f305
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Plugin based library to create window decorations
description: |
    Plugin based library to create window decorations.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - ki18n-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
