name       : kdecoration
version    : 5.20.4
release    : 59
source     :
    - https://cdn.download.kde.org/stable/plasma/5.20.4/kdecoration-5.20.4.tar.xz : 8d1224a50a2e8c0ec24faab4453432eb8083b35a63e479523de95dce644226e8
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Plugin based library to create window decorations
description: |
    Plugin based library to create window decorations.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - ki18n-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
