name       : kdecoration
version    : 5.21.3
release    : 64
source     :
    - https://cdn.download.kde.org/stable/plasma/5.21.3/kdecoration-5.21.3.tar.xz : c5d14b8dd6983f22cbf4d34461e912fd38cd49114d01fb25635d7a1a9c7e4319
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : LGPL-2.1-only
component  : programming
summary    : Plugin based library to create window decorations
description: |
    Plugin based library to create window decorations.
optimize   : lto
builddeps  :
    - ki18n-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
