name       : kdecoration
version    : 5.9.3
release    : 3
source     :
    - http://download.kde.org/stable/plasma/5.9.3/kdecoration-5.9.3.tar.xz : 29120c9263ad4913d20667337bddcb39940cd776ad1c171559b9268715a567fc
license    : LGPL-2.1
component  : programming
summary    : Plugin based library to create window decorations
description: |
    Plugin based library to create window decorations.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
