name       : kdecoration
version    : 5.22.1
release    : 67
source     :
    - https://cdn.download.kde.org/stable/plasma/5.22.1/kdecoration-5.22.1.tar.xz : 939a09ddf73c098f258e6448b7551639b8d94253c083a23c5c8fc3507d08a259
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : LGPL-2.1-only
component  : programming
summary    : Plugin based library to create window decorations
description: |
    Plugin based library to create window decorations.
optimize   : lto
builddeps  :
    - ki18n-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
