name       : kdecoration
version    : 5.11.4
release    : 11
source     :
    - https://cdn.download.kde.org/stable/plasma/5.11.4/kdecoration-5.11.4.tar.xz : 35619d57ffe727eb624e67dc180279536e081955720dd67eea6751395a83706f
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Plugin based library to create window decorations
description: |
    Plugin based library to create window decorations.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
