name       : kdecoration
version    : 5.18.5
release    : 51
source     :
    - https://cdn.download.kde.org/stable/plasma/5.18.5/kdecoration-5.18.5.tar.xz : f09856245f2cb08d9013da4c3128b5438f1e2f58af40031eb547ae765f57a9c8
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Plugin based library to create window decorations
description: |
    Plugin based library to create window decorations.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - ki18n-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
