name       : kdecoration
version    : 5.7.4
release    : 1
source     :
    - http://download.kde.org/stable/plasma/5.7.4/kdecoration-5.7.4.tar.xz : 817ad5fbf497bd838654ae62c5c0b21c4a502a537a4ffd72f3fdeda4f2580c98
license    : LGPL-2.1
component  : programming
summary    : Plugin based library to create window decorations
description: |
    Plugin based library to create window decorations.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
