name       : kdecoration
version    : 5.13.3
release    : 22
source     :
    - https://cdn.download.kde.org/stable/plasma/5.13.3/kdecoration-5.13.3.tar.xz : 49711c61252479d74c5fab75c7935204803b69a4c1a07f368f9218a1fd3d2d6f
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Plugin based library to create window decorations
description: |
    Plugin based library to create window decorations.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - ki18n-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
