name       : kdecoration
version    : 5.17.2
release    : 43
source     :
    - https://cdn.download.kde.org/stable/plasma/5.17.2/kdecoration-5.17.2.tar.xz : 80842366805d38557aac93c747e3a20bcc778dfd41b7fd2fecc96159cb906c11
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Plugin based library to create window decorations
description: |
    Plugin based library to create window decorations.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - ki18n-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
