name       : kdecoration
version    : 5.12.1
release    : 14
source     :
    - https://cdn.download.kde.org/stable/plasma/5.12.1/kdecoration-5.12.1.tar.xz : 3e3a137eb0a056196b8473a601740a892ab15e8dda8debed9461c1fbd83ca823
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Plugin based library to create window decorations
description: |
    Plugin based library to create window decorations.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
