name       : kdecoration
version    : 5.10.1
release    : 5
source     :
    - https://download.kde.org/stable/plasma/5.10.1/kdecoration-5.10.1.tar.xz : 250db707d3c533c03e7dc40e8312fd54db578a743b595d760ab3a5e1a4ef43db
license    : LGPL-2.1
component  : programming
summary    : Plugin based library to create window decorations
description: |
    Plugin based library to create window decorations.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
