name       : kdecoration
version    : 5.18.1
release    : 47
source     :
    - https://cdn.download.kde.org/stable/plasma/5.18.1/kdecoration-5.18.1.tar.xz : 22816ea3407ded2aa82e10d2caa88aa9bf86475d6b6eec39d9564d7dc06013d2
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Plugin based library to create window decorations
description: |
    Plugin based library to create window decorations.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - ki18n-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
