name       : kdecoration
version    : 5.25.3
release    : 82
source     :
    - https://cdn.download.kde.org/stable/plasma/5.25.3/kdecoration-5.25.3.tar.xz : 3ef59443be9b602a85710d0de1d39d9e9f5acc98698c0d13628ad66627b6de2c
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : LGPL-2.1-only
component  : programming
summary    : Plugin based library to create window decorations
description: |
    Plugin based library to create window decorations.
optimize   : lto
builddeps  :
    - kcoreaddons-devel
    - ki18n-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
