name       : kdecoration
version    : 5.11.5
release    : 12
source     :
    - https://cdn.download.kde.org/stable/plasma/5.11.5/kdecoration-5.11.5.tar.xz : 2da1be7a61e9c941cd3e2b01ee8e6bce1012bb2acf10ba6cc9014ee739ae8942
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Plugin based library to create window decorations
description: |
    Plugin based library to create window decorations.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
