name       : kdecoration
version    : 5.8.4
release    : 2
source     :
    - http://download.kde.org/stable/plasma/5.8.4/kdecoration-5.8.4.tar.xz : 84b619de6439256498c5a607a0b8e1781cb3f391e31fa3718dd3451f0e1a9019
license    : LGPL-2.1
component  : programming
summary    : Plugin based library to create window decorations
description: |
    Plugin based library to create window decorations.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
