name       : kdecoration
version    : 5.13.5
release    : 24
source     :
    - https://cdn.download.kde.org/stable/plasma/5.13.5/kdecoration-5.13.5.tar.xz : 1a6bf44f9dce92e6923d3bb0b342790944c078604211caeeaa642556b43be712
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Plugin based library to create window decorations
description: |
    Plugin based library to create window decorations.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - ki18n-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
