name       : kdecoration
version    : 5.12.4
release    : 17
source     :
    - https://cdn.download.kde.org/stable/plasma/5.12.4/kdecoration-5.12.4.tar.xz : d22e54abd40cc3e030e894510e45e11a318f126ba658c708d0a56e58c01a5a5a
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Plugin based library to create window decorations
description: |
    Plugin based library to create window decorations.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
setup      : |
    %patch -p1 < $pkgfiles/0001-Disable-building-unshipped-code.patch
    %cmake .
build      : |
    %make
install    : |
    %make_install
