name       : kdecoration
version    : 5.16.1
release    : 37
source     :
    - https://download.kde.org/stable/plasma/5.16.1/kdecoration-5.16.1.tar.xz : 37d8bd4eb28b268536d7eab88746a6bc37a82e99eade9b3e3ee6663a8aa3263c
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Plugin based library to create window decorations
description: |
    Plugin based library to create window decorations.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - ki18n-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
