name       : kdecoration
version    : 5.10.5
release    : 6
source     :
    - https://download.kde.org/stable/plasma/5.10.5/kdecoration-5.10.5.tar.xz : c355b29165df1d84d640a257ce10c304dd5ba6b46c99e15cb4225dbb747c443c
license    : LGPL-2.1
component  : programming
summary    : Plugin based library to create window decorations
description: |
    Plugin based library to create window decorations.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
