name       : kdecoration
version    : 5.9.5
release    : 4
source     :
    - https://download.kde.org/stable/plasma/5.9.5/kdecoration-5.9.5.tar.xz : d4529161bfe989f4a6c3f7e5dbf0f727119a8f7abe4ae9565fe04504e54352ee
license    : LGPL-2.1
component  : programming
summary    : Plugin based library to create window decorations
description: |
    Plugin based library to create window decorations.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
