name       : kdecoration
version    : 5.14.4
release    : 30
source     :
    - https://cdn.download.kde.org/stable/plasma/5.14.4/kdecoration-5.14.4.tar.xz : f3ffc122b52aae490f4efb1ecc131e2d2575a9305dd8df6adead48892cd4d882
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Plugin based library to create window decorations
description: |
    Plugin based library to create window decorations.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - ki18n-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
