name       : kdecoration
version    : 5.27.5
release    : 87
source     :
    - https://cdn.download.kde.org/stable/plasma/5.27.5/kdecoration-5.27.5.tar.xz : effbf6c5c79802d07fa14f8bd40a9d57bbfc2af2861b6ed596687db48230be42
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : LGPL-2.1-only
component  : programming
summary    : Plugin based library to create window decorations
description: |
    Plugin based library to create window decorations.
optimize   : lto
builddeps  :
    - kcoreaddons-devel
    - ki18n-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
