name       : kdecoration
version    : 5.12.3
release    : 16
source     :
    - https://cdn.download.kde.org/stable/plasma/5.12.3/kdecoration-5.12.3.tar.xz : 5ed358c40ae7d832cc44f7fc4cba21211ba71c8c54817c79a19e64c415c252f7
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Plugin based library to create window decorations
description: |
    Plugin based library to create window decorations.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
