name       : kdecoration
version    : 5.11.0
release    : 7
source     :
    - https://download.kde.org/stable/plasma/5.11.0/kdecoration-5.11.0.tar.xz : 2e6453445a7695c598005110ecedb58a50a9fd8fafcdbd3ba7bf2350210d0399
license    : LGPL-2.1
component  : programming
summary    : Plugin based library to create window decorations
description: |
    Plugin based library to create window decorations.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
