name       : kdecoration
version    : 5.13.1
release    : 20
source     :
    - https://cdn.download.kde.org/stable/plasma/5.13.1/kdecoration-5.13.1.tar.xz : e3f18610a1c21199db449ffce44424e9960815ad33c30254b1ab6fa5c032d0a5
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Plugin based library to create window decorations
description: |
    Plugin based library to create window decorations.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - ki18n-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
